Assignment_1/Models/SkillSet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace Assignment_1.Models
{
    public class SkillSet
    {
        // SkillSet Table
        [Key]
        [Display(Name = "ID:")]
        public int SkillSetID { get; set; }

        [Display(Name = "Name:")]
        [Required(ErrorMessage = "Please Fill This Up!")]
        [StringLength(255, ErrorMessage = "Name Cannot Exceed 255 Characters!")]
        //Custom Validation Attribute for checking skillset name exists
        [ValidateSkillSetExists(ErrorMessage = "This name already exists!")]
        public string SkillSetName { get; set; }

        public List<StudentSkillSetsViewModel> StudentSkillSets{ get; set; }
    }
}

Assignment_1/Controllers/SkillSetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Assignment_1.DAL;
using Assignment_1.Models;
using System.IO;


namespace Assignment_1.Controllers
{
    public class SkillSetController : Controller
    {
        private SkillSetDAL skillSetContext = new SkillSetDAL();
        private StudentDAL studentContext = new StudentDAL();

        //GET:SkillSet/Index
        public ActionResult Index()
        {
            //Stop accessing the action if not logged in or account not in the "Lecturer" Role
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }

            //List<SkillSet> skillSetList = skillSetContext.GetDetails(HttpContext.Session.GetString("LoginID"));
            List<SkillSet> skillSetList = skillSetContext.GetAllSkillSet();
            return View(skillSetList);
        }

        // GET: SkillSet/Create
        public ActionResult Create()
        {
            //Stop accessing in the action if not logged in or account not in the "Lecturer" role
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View("Create");
        }

        // POST: SkillSet/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SkillSet skillSet)
        {
            if (ModelState.IsValid)
            {
                //Add skillset record to database
                skillSet.SkillSetID = skillSetContext.Add(skillSet);

                //Redirect user to SkillSet/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view to display error message
                return View(skillSet);
            }
        }

        //GET: SkillSet/Delete
        public ActionResult Delete(int? id)
        {
            // Stop accessing the action if not logged in// or account not in the "Staff" role
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }

            SkillSet skillSet = skillSetContext.GetDetails(id.Value);
            if (skillSet == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(skillSet);
        }

        // POST: SkillSet/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SkillSet skillSet)
        {
            try
            {
                skillSetContext.Delete(skillSet.SkillSetID);
                return RedirectToAction("Index");
            }
            catch
            {
                ViewData["Message"] = "There are students using this skillset!!!";
                return View();
            }
        }

        // GET: SkillSet/Edit
        public ActionResult Edit(int? id)
        {
            // Stop accessing the action if not logged in or account not in the "Staff" role
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null) //Query string parameter not provided
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }

            SkillSet skillSet = skillSetContext.GetDetails(id.Value);

            if (skillSet == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }

            return View(skillSet);
            
        }

        // POST: SkillSet/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SkillSet skillSet)
        {
            if (ModelState.IsValid)
            {
                //Update SkillSet Record to database
                skillSetContext.Edit(skillSet);
                ViewData["Message"] = "SkillSet Name updated successfully";
                //return RedirectToAction("Index");
            }
            else
            {
                ViewData["Message"] = "Failed to update SkillSet Name";
            }

            //Input validation fails, return to the view to display error message
            return View(skillSet);
        }

        // GET: SkillSet/Search
        public ActionResult Search(int? id)
        {
            // Stop accessing the action if not logged in or account not in the "Staff" role
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }

            StudentSkillSetsViewModel studentSkillVM = new StudentSkillSetsViewModel();
            studentSkillVM.skillSetList = skillSetContext.GetAllSkillSet();
            studentSkillVM.studentskillsList = skillSetContext.GetAllStudentSkills();
            
            // BranchNo (id) present in the query string
            if (id != null)
            {
                ViewData["selectedSkillID"] = id.Value;
                studentSkillVM.studentskillsList = skillSetContext.Search(id.Value);
            }
            else
            {
                ViewData["selectedSkillID"] = "";
            }
            return View(studentSkillVM);
        }

        public ActionResult StudentDetails(int? id)
        {
            if (HttpContext.Session.GetString("Role") != null || HttpContext.Session.GetString("Role") == "Lecturer")
            {
                Student student = skillSetContext.GetStudents(id.Value);
                return View(student);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

    }
}

Assignment_1/Views/SkillSet/Create.cshtml
@model Assignment_1.Models.SkillSet

@{
    ViewData["Title"] = "Create SkillSet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <script src="~/js/SkillSet.js"></script>
</head>

<h4 class="PageTitle">Create new SkillSet Record</h4>
<hr />

<form asp-action="Create" enctype="multipart/form-data">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="SkillSetName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetName" class="form-control" id="name"/>
                <span asp-validation-for="SkillSetName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Submit" class="btn btn-primary" />
                <button type="button" class="btn btn-secondary" onclick="resetSkillSetForm()">Reset</button>
                <span style="color:red;">@ViewData["Message"]</span>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

Assignment_1/Views/SkillSet/Delete.cshtml
@model Assignment_1.Models.SkillSet

@{
    ViewData["Title"] = "Delete SkillSet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="PageTitle">Delete SkillSet</h4>
<hr />

<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure you want to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="SkillSetID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetID" readonly class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="SkillSetName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetName" readonly class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <span style="color:red;">@ViewData["Message"]</span>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

Assignment_1/Views/SkillSet/Edit.cshtml
@model Assignment_1.Models.SkillSet

@{
    ViewData["Title"] = "Edit SkillSet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <script src="~/js/SkillSet.js"></script>
</head>

<h4 class="PageTitle">Edit SkillSet Record</h4>
<hr />

<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="SkillSetID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetID" readonly class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="SkillSetName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetName" class="form-control" id="name" />
                <span asp-validation-for="SkillSetName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save Changes" class="btn btn-primary" />
                <button type="button" class="btn btn-secondary" onclick="resetSkillSetForm()">Reset</button>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <span style="color:red;">@ViewData["Message"]</span>
            </div>
        </div>

        <div>
            <p>
                <a asp-action="Index">Back to List</a>
            </p>
        </div>
    </fieldset>
</form>

Assignment_1/Views/SkillSet/Index.cshtml
@model IEnumerable<Assignment_1.Models.SkillSet>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="PageTitle">View SkillSets</h4>
<hr />

<p>
   <a asp-action="Create">Create New SkillSet</a>
</p>
<br />

<!--Add a partial view to display a list of skillset records in a tabular format.-->
<partial name="~/Views/SkillSet/_ViewSkillSet.cshtml" model="@Model" />

Assignment_1/Views/SkillSet/Search.cshtml
@model Assignment_1.Models.StudentSkillSetsViewModel

@{
    ViewData["Title"] = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="PageTitle">View Student Skills</h3>
<br />

<div class="table-responsive">
    <table id="viewBranch" class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>SkillSetID</th>
                <th>SkillSetName</th>
                <th>StudentID</th>
                <th>StudentName</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (ViewData["selectedSkillID"].ToString() != "")
            {
                <h5>Students with SkillSet @ViewData["selectedSkillID"].ToString()</h5>
                @foreach (var item in Model.studentskillsList)
                {
                    string selectedRow = "";
                    if (ViewData["selectedSkillID"].ToString() == item.SkillSetID.ToString())
                    {
                        // Highlight the selected row
                        selectedRow = "class='table-primary'";
                    }
                    <tr @Html.Raw(selectedRow)>
                        <td>@item.SkillSetID.ToString()</td>
                        <td>@item.SkillSetName</td>
                        <td>@item.StudentID</td>
                        <td>@item.StudentName</td>
                        <td><a asp-action="StudentDetails" asp-controller="SkillSet" asp-route-id="@item.StudentID">Details</a></td>
                    </tr>
                }
            }
            else
            {
                <p>There are no students using this skillset!</p>
            }
        </tbody>
    </table>
</div>
<div>
    <p>
        <a asp-action="Index">Back to List</a>
    </p>
</div>

Assignment_1/Views/SkillSet/StudentDetails.cshtml
@model Assignment_1.Models.Student

@{
    ViewData["Title"] = "Student Dashboard";

    Layout = "~/Views/Shared/_Layout.cshtml";

}

<html>
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Student Dashboard</title>

    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel='stylesheet' href='~/css/student_dashboard.css'>
</head>

<body>
    <a asp-action="StudentDetails"></a>
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="StudentID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext"> @Html.Display("StudentID")</div>
        </div>
        <div class="form-group row">
            <label asp-for="StudentName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext"> @Html.Display("StudentName")</div>
        </div>
        @*<div class="form-group row">
            <label asp-for="StudentPhoto" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <img src="~/images/Student/@Model.StudentPhoto" style="width:15vw" />
            </div>
        </div>*@
        <div class="form-group row">
            <label asp-for="StudentCourse" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext"> @Html.Display("StudentCourse")</div>
        </div>
        <div class="form-group row">
            <label asp-for="StudentDescription" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext"> @Html.Display("StudentDescription")</div>
        </div>
        <div class="form-group row">
            <label asp-for="StudentAchievement" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext"> @Html.Display("StudentAchievement")</div>
        </div>
        <div class="form-group row">
            <label asp-for="StudentEmailAddr" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext"> @Html.Display("StudentEmailAddr")</div>
        </div>
        <div class="form-group row">
            <label asp-for="StudentExternalLink" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext"> @Html.Display("StudentExternalLink")</div>
        </div>

    </fieldset>
</body>
</html>

Assignment_1/Views/SkillSet/_ViewSkillSet.cshtml
@model IEnumerable<Assignment_1.Models.SkillSet>

    <head>
        <!-- Reference to Bootstrap CSS, JavaScript/JQuery files -->
        <link rel='stylesheet' href='~/lib/bootstrap/dist/css/bootstrap.min.css'>
        <script src='~/lib/jquery/dist/jquery.min.js'></script>
        <script src="~/js/popper.min.js"></script>
        <script src='~/lib/bootstrap/dist/js/bootstrap.min.js'></script>
    </head>

@if (Model.ToList().Count > 0)
{
    <div class="container" style="background:antiquewhite; border:solid black">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-sm-4 col-sm-1">
                    <div class="card" style="max-width:100%; height:300px; margin-bottom:5%; margin-top:5%;">
                        <div class="card-body">
                            <h6 class="mw-100 text-center" style="font-size:150%; font:bold">@item.SkillSetID.ToString().  @item.SkillSetName</h6>
                            @*@{string imageFileName = item.SkillSetName + ".jpg";}<img src="~/images/SkillSets/@imageFileName" class="mx-auto d-block" style="width:50%; margin-top:3%" />*@
                            <div class="text-center">
                                <p>
                                    <div href="#" class="btn btn-outline-primary" style="font-size:80%; background-color:greenyellow"><a asp-action="Edit" asp-controller="SkillSet" asp-route-id="@item.SkillSetID">Edit</a></div> |
                                    <div href="#" class="btn btn-outline-danger" style="font-size:80%; background-color:red"><a asp-action="Delete" asp-controller="SkillSet" asp-route-id="@item.SkillSetID">Delete</a></div> |
                                    <div href="#" class="btn btn-outline-danger" style="font-size:80%; background-color:lightblue"><a asp-action="Search" asp-controller="SkillSet" asp-route-id="@item.SkillSetID">Search</a></div>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}
else
{
    <span style="color:red">No SkillSet record found!</span>
}